### ISSUE TITLE
Fix incorrect Webpack override example

### ISSUE THREAD

**Issue by chrisvxd** [chrisvxd/story2sketch#1]
The webpack override example in the README, used for detecting stories, doesn't get picked up and results in the error

```
ReferenceError: preview is not defined
```

Need to update docs to specify that you need full control mode.

**Comment by oliverbenns** [comment]
I tried specifying my own config. This fixed the first issue of `preview is not defined` but not now it outputs `preview.getStorybook is not a function`.
```
module.exports = (storybookBaseConfig, configType) => {
  storybookBaseConfig.output = {
    ...storybookBaseConfig.output,
    library: "[name]"
  }

  // ...other config mutating storybookBaseConfig here

  return storybookBaseConfig
}
```

**Comment by chrisvxd** [comment]
Hi @oliverbenns, which version of storybook are you using? I think `getStorybook` is only exported in 3.3+.

As a workaround, you could export the function manually in your `./storybook/config.js` file, like so:

```js
import { getStorybook } from "@storybook/react";

...

export { getStorybook }
```

Let me know if that works.

**Comment by chrisvxd** [comment]
Closed in 9f5a615

**Comment by oliverbenns** [comment]
Thanks @chrisvxd ! Apologies for not getting back to you. 🎉

**Comment by chrisvxd** [comment]
Not to worry @oliverbenns. Did you get it working?

**Comment by oliverbenns** [comment]
This was part of a hack day so unfortunately was abandoned. We'll look to revisit this at some point. 👍

**Comment by siddharthkp** [comment]
Update: Doesn't without `export { getStorybook }` in `3.3.15`

Might want to include it in the docs

**Comment by chrisvxd** [comment]
Thanks @siddharthkp, I'll look into this and correct docs this week.
