### ISSUE TITLE
Add note on "Navigation timeout exceeded"

### ISSUE THREAD

**Issue by nettiopsu** [chrisvxd/story2sketch#19]
Hello, I am trying to export a Storybook, which has 38 examples

For some reason, it goes through 4 of them and then it collapses on error Navigation Timeout Exceeded: 30000ms exceeded

According to the source code, it happens in getSymbolsForStory:

`await page.goto(builtUrl, {
      waitUntil: "networkidle2"
});`

and it says before showing timeout error:
TypeError: Cannot read property 'goto' of undefined

I tried to change the order of storiesOfComponent, but it always stops on 4th page no matter what. 4 generated pages look completely fine after using exported file in Sketch

Any ideas on it? Is it puppeteer issue?

**Comment by chrisvxd** [comment]
Hey @nettiopsu! I've also encountered this in the past, and solved it by tweaking the concurrency.

Could you try reducing the concurrency to 2 or 1? https://github.com/chrisvxd/story2sketch#api

Background: story2sketch runs a headless chrome instance with multiple tabs. Concurrency controls the number of open tabs at any one time.

**Comment by chrisvxd** [comment]
Closing in favour of #67
