### ISSUE TITLE
Allow options to be passed to Puppeteer

### ISSUE THREAD

**Issue by andrewshawcare** [chrisvxd/story2sketch#36]
I'm using Docker in my project and receiving the following error:

`[0619/122651.197333:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.`

I'd like to allow Puppeteer to be launched with the `--no-sandbox` argument. Ideally, this could be implemented in [this line](https://github.com/chrisvxd/story2sketch/blob/37dc447126d4ff0cc376b0519632104419142b23/src/server/Story2sketch.js#L66) as:

`this.browser = await puppeteer.launch(this.puppeteerOptions);`

Where `this.puppeteerOptions` would be `{ args: ["--no-sandbox"] }`

**Comment by andrewshawcare** [comment]
Any updates on this?

**Comment by andrewshawcare** [comment]
Further information regarding the need to set `--no-sandbox`: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by andrewshawcare** [comment]
Apparently the SUID sandbox has been _almost_ completely removed: https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md

**Comment by chrisvxd** [comment]
Sorry for the delay @andrewshawcare, have been away on holiday.

I'll try and have a look into this for you. Passing properties via the story2sketch config sounds like a great idea.

**Comment by chrisvxd** [comment]
Just saw your PR! Thanks. Will review that.
