### ISSUE TITLE
doesnt work with some react-bootstrap components

### ISSUE THREAD

**Issue by TonyMasterR** [chrisvxd/story2sketch#50]
i use React to display UI, exactly react-bootstrap components library, when i try to generate asketch.json via CLI, the process stops on 40%, some components that displays properly in storybook don't get into asketch.json

need help with that
<img width="1440" alt="screenshot 2018-11-23 at 16 29 18" src="https://user-images.githubusercontent.com/13406235/48946008-5b621c00-ef3d-11e8-99c4-8a41d37da0ef.png">

**Comment by TonyMasterR** [comment]
i found solution, the problem is wtih concurrency, I set it to value 2 and it works well

**Comment by Adomas202** [comment]
I have the same issue. However, setting concurrency to 2 doesn't make a difference 😿.

**Comment by chrisvxd** [comment]
Glad you solved it @TonyMasterR. I need to update the default for the project for 2, since it's a safer default than 4.

**Comment by Adomas202** [comment]
Also, I would like to add that for me only when I add concurrency 2 before the URL and other configs in launch command I am not getting that error.
For instance: story2sketch --concurrency 2 --url https://localhost:9001/iframe.html --output stories.asketch.json
