### ISSUE TITLE
`querySelector` dept

### ISSUE THREAD

**Issue by beautifwhale** [chrisvxd/story2sketch#57]
Just playing around with this and I dont think the `querySelector` works as expected. 

Using 
```
  querySelector: '#root div div',
```
Only selects '#root div', I'll do more testing...

**Comment by damorton** [comment]
Maybe its just my understanding of the `querySelector ` so what I want do is only output whats inside the `#root div div` to sketch, but instead its outputting everything under `#root` wether I use `#root div div` or '#root'

**Comment by damorton** [comment]
```
module.exports = {
  output: 'docs/react.asketch.json',
  input: 'docs/iframe.html',
  pageTitle: 'Stories',
  querySelector: '#root div div',
  verbose: true,
  stories: [
    {
      kind: 'Components/Card',
      stories: [
        {
          name: 'Card',
        },
      ],
    },
  ],
};
```

Getting 

![screenshot 2018-12-11 at 10 59 54](https://user-images.githubusercontent.com/3397660/49796187-ea3fa880-fd33-11e8-8b66-9342b3672a76.png)

Based on the above config `#root div div` the Sketch output includes the Implementation text, but this is not inside `#root div div`. 

<img width="1178" alt="screenshot 2018-12-11 at 11 02 07" src="https://user-images.githubusercontent.com/3397660/49796303-3c80c980-fd34-11e8-95c1-7c524dc2cc32.png">

**Comment by chrisvxd** [comment]
@damorton I don't think you're misinterpreting the `querySelector` functionality, but I'm struggling to reproduce.

Is it possible to get access to your source to investigate? If not, would you be able to provide me with a code snippet so I can attempt to reproduce?

**Comment by chrisvxd** [comment]
@beautifwhale updating comment handle because I think you renamed.
