### ISSUE TITLE
Background images rendered outside of symbol when using background position

### ISSUE THREAD

**Issue by acrossell-hedgehog** [chrisvxd/story2sketch#62]
If an element has a background image position set, the background image is rendered outside of the symbols bounds when imported into Sketch. Is there a known workaround for this?

**Comment by chrisvxd** [comment]
Hi @acrossell-hedgehog, this sort of functionality is generally handled by the core dependency `html-sketchapp`. I'm due to upgrade to the latest version, which may address this issue, but I haven't had a chance to investigate yet. Will let you know :)

**Comment by acrossell-hedgehog** [comment]
That's great news Chris! I'm looking to put this at the center of our design process and this is the only hurdle that the design team may have an issue with. I can't wait to see it drop into place!

**Comment by chrisvxd** [comment]
Hey @acrossell-hedgehog - I'm currently investigating this and I'm unable to reproduce the scenario you're describing. I have:

```jsx
      <div
        className="my-div"
        style={{
          backgroundImage: "url(https://picsum.photos/200/300/?random)",
          backgroundRepeat: "no-repeat",
          backgroundPositionX: 50,
          backgroundPositionY: 50,
          border: "2px solid hotpink",
          display: "inline-block",
          padding: 50
        }}
      >
        Hello, world!
      </div>
```

In storybook:

<img width="200" alt="Screenshot 2019-04-02 10 52 30" src="https://user-images.githubusercontent.com/985961/55393574-6c4b1b80-5535-11e9-8851-7ba7329ced25.png">

In sketch (ignore changing image):

<img width="340" alt="Screenshot 2019-04-02 10 53 08" src="https://user-images.githubusercontent.com/985961/55393621-81c04580-5535-11e9-9539-f57d7d0c9e24.png">

Are you able to share your styles?

**Comment by acrossell-hedgehog** [comment]
Hi @chrisvxd,

I believe the issue arises when background size is set to cover or contain

**Comment by chrisvxd** [comment]
@acrossell-hedgehog I've noticed some issues with `background-size: contain`, but I'm unable to reproduce exactly what you're talking about, or any issues with `cover`. **I can't really diagnose further without a concrete CSS example with screenshots describing what you're encountering**.

Having said that, this is more than likely an issue with [`html-sketchapp`](https://github.com/brainly/html-sketchapp) (the thing that handles the actual HTML -> Sketch conversion for story2sketch), so it might be worth us opening a ticket there and cross referencing here.

**Comment by acrossell-hedgehog** [comment]
Thanks @chrisvxd. It does seem to be center and contain that present the issue. Using pixel positioning is a fine workaround. I'll raise this on html-sketchapp. I've noticed a few people are looking for a solution to this.

**Comment by acrossell-hedgehog** [comment]
The problem seems to be with background-position: center
