### ISSUE TITLE
Change default concurrency from 4 to 2

### ISSUE THREAD

**Issue by Adomas202** [chrisvxd/story2sketch#67]
As I see some people, me included, have issues with concurrency. By default it is set to 4, however, most of the people report that with --concurrency set to 2 some main issues disappear. My suggestion would be to change default setting and update API documentation.

**Comment by acrossell-hedgehog** [comment]
Yeah I had to make that adjustment too. Seems a sensible suggestion.

**Comment by chrisvxd** [comment]
Yup thanks @Adomas202. This has been on my radar for a while, but haven't got around to it. Will update today.
