### ISSUE TITLE
How do you debug why things aren't working?

### ISSUE THREAD

**Issue by leerob** [chrisvxd/story2sketch#68]
I've been trying everything I can do to get this working with no luck. Whenever I import the file into Sketch, it's always empty. 

I tried doing the custom config and only selecting a story and that didn't seem to change anything. Is this because I'm using Storybook 5? 

So my question is: How can I debug when the import into Sketch doesn't output anything?

**Comment by chrisvxd** [comment]
Hi @leerob. Unfortunately story2sketch doesn't do a great job at making it easy to debug.

There's a myriad of technologies at play, and some can be a little brittle (for example, html-sketchapp), and errors often to get swallowed up and things fail silently.

I'd really like to improve this, so I've just opened #70.

So I can help with your _particular_ issue, are you able to share your storybook setup with me?

**Comment by acrossell-hedgehog** [comment]
@leerob, I've also been having issues debugging. I've found sketch dev tools very helpful with import issues.

https://github.com/skpm/sketch-dev-tools
