### ISSUE TITLE
Upgrade to html-sketchapp v4.0.1 

### ISSUE THREAD

**Issue by acrossell-hedgehog** [chrisvxd/story2sketch#69]
There seems to be an issue in html-sketchapp where SVG's comprising of only one layer fail to import and cause the asketch import to fail completely.

https://github.com/brainly/html-sketchapp/issues/165
https://github.com/brainly/html-sketchapp/issues/137 

v4.0.1 seems to have a fix in place. Are there any plans to upgrade the version in story2sketch?

**Comment by chrisvxd** [comment]
Always plan to stay up to date so will investigate shortly.

**Comment by chrisvxd** [comment]
Have upgraded in https://github.com/chrisvxd/story2sketch/commit/4db415767dcaddf74b68c14f369fec8a1eaf4cfe. Will do release soon, once other issues resolved.

**Comment by acrossell-hedgehog** [comment]
Cheers @chrisvxd!

**Comment by chrisvxd** [comment]
@acrossell-hedgehog Other issues haven't had any response so I've just released v1.6.0, including latest html-sketchapp!
